# Generated by Django 4.0.7 on 2022-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_productdeals_price_productdeals_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('banner', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
