# Generated by Django 4.0.7 on 2022-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_companyinfo_popularsearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
