# Generated by Django 4.0.7 on 2022-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_quantity',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
